### ISSUE TITLE
todo, goal 엔티티 세팅

### ISSUE THREAD

**Issue by uijin-j** [DDu-Du-DDu-Du/back-end#13]
## Description
저와 예림 언니 작업 모두에서 `goal`, `todo` 엔티티가 필요해 미리 셋업한 뒤 merge하고, 각자 작업을 시작하기로 했습니다!

## Jira Issue Link
NA

## To Be

- [x] `V1__schema.sql`에 goal 테이블 ddl 작성
- [x] `V1__schema.sql`에 todo 테이블 ddl 작성
- [x] goal 엔티티 클래스 생성
- [x] goal 엔티티 클래스 테스트 코드 작성
- [x] todo 엔티티 클래스 생성
- [x] todo 엔티티 클래스 테스트 코드 작성
